[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd website && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"
